module input_mod

    use constants_mod
    implicit none

    !Boundaries of the simulation box.
    !This can be: "closed", "periodic", "pml"
    character(len=10) :: mxll_boundaries(3) = "closed"

    !List of names of the fields to print in the output files.
    !This can be: "Ex", "Ey", "Ez", "Hx", "Hy", "Hz"
    character(len=10)  :: mxll_print_field_list(6) = "none" 
    
    !Number of dimensions of the simulation box. This can be 1, 2 or 3.
    integer           :: mxll_dimensions = 1
    
    !Number of PML layers in every direction of the simulation box.
    integer           :: mxll_n_pml=20

    !Grid steps in every direction.     
    real(dp)          :: mxll_dr
   
    !Dimensions of the simulation box in units of dr.
    real(dp)          :: mxll_box_size(3)
    
    !List of frequencies of each optimization problem.
    real(dp)          :: mxll_freq_list(100)
    
    !List of permittivity values of each optimization problem.
    real(dp)          :: mxll_eps_Re(100) = 1.0_dp
    real(dp)          :: mxll_eps_Im(100) = 0.0_dp
    
    !Number of points for the finite difference derivative used in the optimization.
    !This can be 2, 4, 6, or 8.
    integer           :: mxll_accuracy_derivatives = 2

    !Number of optimization problems to solve within the same
    !function of merit.
    integer           :: design_n_opt_problems
    
    !Maximum number of iteration steps for the optimization.
    integer           :: design_max_iter_steps = 100

    !If true, the optimization will scan every term from
    !delta_rho. Once this does not improve the objective function,
    !the optimization will continue with the next beta value or
    !stop if there are no more beta values to scan.
    logical           :: design_converge_optimization = .true.

    !If true, the optimization will restart from a restart file.
    logical           :: design_restart = .false.

    !If true, the optimization will print restart files before changing beta.
    logical           :: design_print_restart = .false.

    !IF design_print_restart is true, this variable controls the frequency of the restart files.
    integer           :: design_restart_freq = 10

    !If true, the optimization will use one stepest descent step to generate the initial guess
    !for rho.
    logical           :: design_apply_grad_rho_init = .false.
    
    !drho value used in the first step if design_apply_grad_rho_init is true in the optimization. 
    !Being rho the design variable and drho the step size of the optimization.
    real(dp)          :: design_drho

    !List of beta values to scan in the optimization. 
    real(dp)          :: design_beta(50)
    
    !Initial value of the design variable rho for the optimization.
    real(dp)          :: design_rho_init = 0.0_dp

    !This variable control the position of the binary function in the optimization.
    !It is not recomended to change its value. 
    real(dp)          :: design_eta = 0.5_dp

    !This variable control the gaussian function used over rho, to give
    !more dimension to the optimization variable.
    real(dp)          :: design_sigma_rho = 1.0_dp

    !Maximum number of iteration steps for the BiCGSTAB_L solver 
    !used in the optimization.
    integer           :: design_bicgstab_max_iter = 1000

    !Number of L parameter of the BiCGSTAB_L solver.
    !L=1 corresponds to the standard BiCGSTAB solver.
    integer           :: design_bicgstab_l_term = 4

    !Tolerance for the BiCGSTAB_L solver used in the optimization.
    real(dp)          :: design_bicgstab_tol = 1.0d-6

    !Number of MPI processes per axis. This is only used 
    !if the code is compiled with MPI support.
    integer           :: mpi_procs_per_axis(3) = 1

    ! Parameters for the L-BFGS-B optimization algorithm.
    ! Number of corrections to approximate the inverse hessian matrix.
    integer           :: design_lbfgsb_m_opt = 5

    ! It controls the frequency and type of output generated:<ul>
    !   - iprint<0    no output is generated.
    !   - iprint=0    print only one line at the last iteration.
    !   - 0<iprint<99 print also f and |proj g| every iprint iterations.
    !   - iprint=99   print details of every iteration except n-vectors.
    !   - iprint=100  print also the changes of active set and final x.
    !   - iprint>100  print details of every iteration including x and g.
    !   - iprint > 0, the file iterate.dat will be created to summarize the iteration.
    integer           :: design_lbfgsb_iprint = -1

    !     factr On entry factr >= 0 is specified by the user.  The iteration
    !     will stop when (f^k - f^{k+1})/max{|f^k|,|f^{k+1}|,1} <= factr*epsmch
    !     where epsmch is the machine precision, which is automatically
    !     generated by the code.
    !     Typical values for factr:
    !        - 1.d+12 for low accuracy.
    !        - 1.d+7  for moderate accuracy.
    !        - 1.d+1 for extremely high accuracy.
    !  On exit factr is unchanged.
    real(dp)          :: design_lbfgsb_factr = 1.0d7

    !  pgtol On entry pgtol >= 0 is specified by the user.  The iteration
    !  will stop when max{|proj g_i | i = 1, ..., n} <= pgtol
    !  where pg_i is the ith component of the projected gradient.
    !  On exit pgtol is unchanged.
    real(dp)          :: design_lbfgsb_pgtol = 1.0d-5

contains

!###################################################################################################

subroutine read_input_file(boundaries, restart, converge_optimization, n_opt_problems,        &
                           max_iter_steps, dimensions, n_pml, grid_Ndims, dr, freq_list,      &
                           eps_Re, eps_Im, delta_rho, beta, eta, rho_init, sigma_rho, mpi_dims, &
                           n_beta_steps, n_accuracy_der, bicgstab_max_iter, &
                           bicgstab_l_term, bicgstab_tol, lbfgsb_m_opt, lbfgsb_iprint, lbfgsb_factr, &
                           lbfgsb_pgtol, print_field_list, print_restart, restart_freq, apply_grad_rho_init)
    
    integer   , intent(out) :: boundaries(3)
    logical   , intent(out) :: restart
    logical   , intent(out) :: converge_optimization
    logical   , intent(out) :: print_restart
    logical   , intent(out) :: apply_grad_rho_init
    integer   , intent(out) :: restart_freq
    integer   , intent(out) :: n_opt_problems
    integer   , intent(out) :: max_iter_steps
    integer   , intent(out) :: dimensions
    integer   , intent(out) :: n_pml
    integer   , intent(out) :: grid_Ndims(3)
    integer   , intent(out) :: n_accuracy_der
    integer   , intent(out) :: print_field_list(6)
    real(dp)  , intent(out) :: dr
    real(dp)  , intent(out) :: freq_list(100)
    real(dp)  , intent(out) :: eps_Re(100)
    real(dp)  , intent(out) :: eps_Im(100)
    real(dp)  , intent(out) :: delta_rho
    real(dp)  , intent(out) :: beta(50)
    real(dp)  , intent(out) :: eta
    real(dp)  , intent(out) :: rho_init
    real(dp)  , intent(out) :: sigma_rho
    real(dp)  , intent(out) :: bicgstab_tol
    real(dp)  , intent(out) :: lbfgsb_factr
    real(dp)  , intent(out) :: lbfgsb_pgtol
    integer   , intent(out) :: mpi_dims(3)
    integer   , intent(out) :: n_beta_steps
    integer   , intent(out) :: bicgstab_max_iter
    integer   , intent(out) :: bicgstab_l_term
    integer   , intent(out) :: lbfgsb_m_opt
    integer   , intent(out) :: lbfgsb_iprint


    integer :: ierr, funit
    integer :: i

    namelist /MARADO/ mxll_boundaries, mxll_dimensions, mxll_n_pml, mxll_box_size, mxll_dr, &
                      mxll_freq_list, mxll_eps_Re, mxll_eps_Im, mxll_print_field_list,      &
                      design_n_opt_problems, design_max_iter_steps,                         &
                      design_converge_optimization, design_restart,  design_drho,           &
                      design_beta, design_eta, design_rho_init, design_sigma_rho,           &
                      design_bicgstab_max_iter, design_bicgstab_l_term,                     &
                      design_bicgstab_tol, mpi_procs_per_axis, mxll_accuracy_derivatives,   &
                      design_print_restart, design_lbfgsb_factr, design_lbfgsb_pgtol,       &
                      design_lbfgsb_m_opt, design_lbfgsb_iprint, design_restart_freq,       &
                      design_apply_grad_rho_init

    ! Check whether file exists.
    inquire (file="inp", iostat=ierr)

    if (ierr /= 0) then
        write (*, '("Error: input file inp does not exist")')
        error stop
    end if

    ! Open and read Namelist file.
    open (action='read', file="inp", iostat=ierr, newunit=funit)
    read (nml=MARADO, iostat=ierr, unit=funit)
    if (ierr /= 0) write (*, '("Error: invalid Namelist format")')

    close (funit)

    mpi_dims = 1

#ifdef USE_MPI

    mpi_dims(1) = mpi_procs_per_axis(1)
    mpi_dims(2) = mpi_procs_per_axis(2)
    mpi_dims(3) = mpi_procs_per_axis(3)

    if (mxll_dimensions > 1) then
        grid_Ndims(1)  = int(mxll_box_size(1)/mxll_dr/mpi_dims(1))
        grid_Ndims(2)  = int(mxll_box_size(2)/mxll_dr/mpi_dims(2))
        grid_Ndims(3)  = int(mxll_box_size(3)/mxll_dr/mpi_dims(3))
    else if (mxll_dimensions == 1) then
        grid_Ndims(1)  = int(mxll_box_size(1)/mxll_dr)
        grid_Ndims(2)  = int(mxll_box_size(2)/mxll_dr)
        grid_Ndims(3)  = int(mxll_box_size(3)/mxll_dr)
    end if
#else
    
    grid_Ndims(1)  = int(mxll_box_size(1)/mxll_dr)
    grid_Ndims(2)  = int(mxll_box_size(2)/mxll_dr)
    grid_Ndims(3)  = int(mxll_box_size(3)/mxll_dr)

#endif

    dimensions            = mxll_dimensions
    n_pml                 = mxll_n_pml
    dr                    = mxll_dr
    freq_list             = 2*pi*mxll_freq_list
    eps_Re                = mxll_eps_Re
    eps_Im                = mxll_eps_Im
    n_opt_problems        = design_n_opt_problems
    max_iter_steps        = design_max_iter_steps
    converge_optimization = design_converge_optimization
    restart               = design_restart
    print_restart         = design_print_restart
    restart_freq          = design_restart_freq
    apply_grad_rho_init   = design_apply_grad_rho_init
    delta_rho             = design_drho
    beta                  = design_beta
    eta                   = design_eta
    rho_init              = design_rho_init
    sigma_rho             = design_sigma_rho
    bicgstab_max_iter     = design_bicgstab_max_iter
    bicgstab_L_term       = design_bicgstab_l_term
    bicgstab_tol          = design_bicgstab_tol
    lbfgsb_m_opt          = design_lbfgsb_m_opt
    lbfgsb_iprint         = design_lbfgsb_iprint
    lbfgsb_factr          = design_lbfgsb_factr
    lbfgsb_pgtol          = design_lbfgsb_pgtol
    

    do i = 1, 3
        select case (mxll_boundaries(i))
        case ("closed")
            boundaries(i) = CLOSE_BOUNDARIES
        case ("periodic")
            boundaries(i) = PERIODIC_BOUNDARIES
        case ("pml")
            boundaries(i) = PML_BOUNDARIES
        case default
            write (*, '("Error: invalid boundary condition in axis ", I0)') i
            error stop
        end select
    end do
    
    i=1
    n_beta_steps = 0
    do while (beta(i) /= 0.0_dp .and. i < size(beta))
        n_beta_steps = n_beta_steps + 1
        i = i + 1
    end do
    
    n_accuracy_der        = int(mxll_accuracy_derivatives/2)

    if (n_accuracy_der /= 1 .and. n_accuracy_der /= 2 .and. n_accuracy_der /= 3 .and. &
        n_accuracy_der /= 4) then
        write (*, '("Error: invalid number of points for finite difference derivative: ", I0)') &
               mxll_accuracy_derivatives
        error stop
    end if

    do i = 1, 6
        select case (mxll_print_field_list(i))
        case ("none")
            print_field_list(i) = PRINT_NONE
        case ("Ex")
            print_field_list(i) = PRINT_Ex 
        case ("Ey")
            print_field_list(i) = PRINT_Ey
            if (mxll_dimensions == 1) then
                write (*, '("Warning: field Ey cannot be printed in 1D simulation box")')
                print_field_list(i) = PRINT_NONE
            end if
        case ("Ez")
            print_field_list(i) = PRINT_Ez
            if (mxll_dimensions == 1) then
                write (*, '("Warning: field Ez cannot be printed in 1D simulation box")')
                print_field_list(i) = PRINT_NONE
            end if
        case ("Hx")
            print_field_list(i) = PRINT_Hx
            if (mxll_dimensions == 1) then
                write (*, '("Warning: field Hx cannot be printed in 1D simulation box")')
                print_field_list(i) = PRINT_NONE
            end if
        case ("Hy")
            print_field_list(i) = PRINT_Hy
        case ("Hz")
            print_field_list(i) = PRINT_Hz
            if (mxll_dimensions == 1) then
                write (*, '("Warning: field Hz cannot be printed in 1D simulation box")')
                print_field_list(i) = PRINT_NONE
            end if
        case default
            write (*, '("Error: invalid field name to print in axis ", a)') mxll_print_field_list(i) 
            error stop
        end select
    end do

end subroutine read_input_file

!###################################################################################################

end module input_mod